// Generated by CoffeeScript 1.6.3
var fs, http, https, socketio, start;

http = require('http');

https = require('https');

fs = require('fs');

socketio = require('socket.io');

module.exports.start = start = function(opts, handler) {
  var server, transport;
  if ((opts.cert != null) && (opts.key != null)) {
    try {
      transport = 'https';
      server = https.createServer({
        key: fs.readFileSync(opts.key),
        cert: fs.readFileSync(opts.cert)
      }, handler);
      return {
        server: server,
        transport: transport
      };
    } catch (_error) {}
  }
  transport = 'http';
  server = http.createServer(handler);
  return {
    server: server,
    transport: transport
  };
};

module.exports.listen = function(opts, callback) {
  var io, server, transport, _ref;
  opts || (opts = {});
  opts.port || (opts.port = null);
  opts.address || (opts.address = 'localhost');
  if (opts.server == null) {
    _ref = start(opts), server = _ref.server, transport = _ref.transport;
  }
  server || (server = opts.server);
  io = socketio.listen(server);
  io.configure(function() {
    return io.set('log level', opts.loglevel || 1);
  });
  if (opts.server == null) {
    server.on('error', function(error) {
      return callback(error);
    });
    server.listen(opts.port, opts.address, function() {
      var address, port, _ref1;
      _ref1 = server.address(), address = _ref1.address, port = _ref1.port;
      console.log('HUB @ %s://%s:%s', transport, address, port);
      return callback(null, {
        transport: transport,
        address: address,
        port: port
      });
    });
  }
  return io;
};
