// Generated by CoffeeScript 1.6.3
var Connector, alreadyDefined, connectRejected, deferred, disconnected, hostname, notifier, reservedCapsule, terminal, testable, undefinedArg, _ref;

hostname = require('os').hostname;

deferred = require('also').deferred;

notifier = require('../notifier');

Connector = require('./connector');

_ref = require('../errors'), terminal = _ref.terminal, reservedCapsule = _ref.reservedCapsule, undefinedArg = _ref.undefinedArg, alreadyDefined = _ref.alreadyDefined, connectRejected = _ref.connectRejected, disconnected = _ref.disconnected;

testable = void 0;

module.exports._client = function() {
  return testable;
};

module.exports.client = function(config) {
  var api, local, type;
  if (config == null) {
    config = {};
  }
  for (type in config.capsules) {
    if (type.match(/^connect$|^handshake$|^accept$|^reject$|^disconnect$|^resume$|^capsule$|^nak$|^ack$|^error$/)) {
      throw reservedCapsule(type);
    }
  }
  testable = local = {
    Notifier: notifier.notifier(config),
    clients: {},
    create: deferred(function(_arg, originName, opts, callback) {
      var already, client, error, notify, reject, resolve, socket, transit, version, _fn;
      reject = _arg.reject, resolve = _arg.resolve, notify = _arg.notify;
      if (opts == null) {
        opts = {};
      }
      try {
        if (typeof originName !== 'string') {
          throw undefinedArg('originName');
        }
        if (local.clients[originName] != null) {
          throw alreadyDefined('originName', originName);
        }
        if (!((opts.connect != null) && typeof opts.connect.port === 'number')) {
          throw undefinedArg('opts.connect.port');
        }
        client = local.Notifier.create(originName);
        local.clients[originName] = client;
      } catch (_error) {
        error = _error;
        return terminal(error, reject, callback);
      }
      opts.context || (opts.context = {});
      opts.context.hostname = hostname();
      opts.context.pid = process.pid;
      socket = Connector.connect(opts.connect);
      client.connection || (client.connection = {});
      client.connection.state = 'pending';
      client.connection.stateAt = Date.now();
      already = false;
      _fn = function(type) {
        return socket.on(type, function(payload) {
          if (typeof client[type] !== 'function') {
            process.stderr.write("notice undefined capsule type '" + type + "'");
            return;
          }
          return client[type](payload);
        });
      };
      for (type in config.capsules) {
        if (type === 'control') {
          continue;
        }
        _fn(type);
      }
      version = 1;
      transit = {};
      client.use({
        title: 'outbound socket interface',
        last: true
      }, function(next, capsule) {
        /* grep PROTOCOL1 encode*/

        var control, header;
        header = [version];
        control = {
          type: capsule._type,
          uuid: capsule._uuid,
          "protected": capsule._protected,
          hidden: capsule._hidden
        };
        socket.emit('capsule', header, control, capsule.all);
        transit[capsule._uuid] = {
          next: next
        };
        return process.nextTick(function() {
          return next.notify({
            _type: 'control',
            control: 'transmitted',
            capsule: capsule
          });
        });
      });
      socket.on('ack', function(control) {
        var next, uuid;
        try {
          uuid = control.uuid;
          next = transit[uuid].next;
        } catch (_error) {
          error = _error;
          process.stderr.write('notice: invalid or unexpected ack');
          return;
        }
        return next();
      });
      socket.on('nak', function(control) {
        return console.log({
          nak: control
        });
      });
      socket.on('connect', function() {
        if (client.connection.state === 'interrupted') {
          client.connection.state = 'resuming';
          client.connection.stateAt = Date.now();
          socket.emit('resume', originName, opts.connect.secret || '', opts.context || {});
          return;
        }
        client.connection.state = 'connecting';
        client.connection.stateAt = Date.now();
        return socket.emit('handshake', originName, opts.connect.secret || '', opts.context || {});
      });
      socket.on('accept', function() {
        var _base;
        if (client.connection.state === 'resuming') {
          client.connection.state = 'accepted';
          client.connection.stateAt = Date.now();
          (_base = client.connection).interruptions || (_base.interruptions = {
            count: 0
          });
          client.connection.interruptions.count++;
          return;
        }
        client.connection.state = 'accepted';
        client.connection.stateAt = Date.now();
        resolve(client);
        if (typeof callback === 'function') {
          return callback(null, client);
        }
      });
      socket.on('reject', function(rejection) {
        /* it may happen that the disconnect occurs before the reject, making the rejection reason 'vanish'*/

        terminal(connectRejected(originName, rejection), reject, callback);
        return already = true;
      });
      socket.on('disconnect', function() {
        if (client.connection.state !== 'accepted') {
          delete local.clients[originName];
          if (!already) {
            terminal(disconnected(originName), reject, callback);
          }
          already = true;
          return;
        }
        client.connection.state = 'interrupted';
        client.connection.stateAt = Date.now();
      });
      return socket.on('error', function(error) {
        if (!((client.connection != null) && client.connection.state === 'pending')) {
          console.log('TODO: handle socket error after connect|accept');
          console.log(error);
          return;
        }
        delete local.clients[originName];
        setTimeout((function() {
          reject(error);
          if (typeof callback === 'function') {
            if (!already) {
              callback(error);
            }
            return already = true;
          }
        }), opts.connect.errorWait || 2000);
      });
    })
  };
  return api = {
    create: local.create
  };
};
