// Generated by CoffeeScript 1.6.3
var ioclient;

ioclient = require('socket.io-client');

module.exports.connect = function(opts) {
  if (opts.rejectUnauthorized != null) {
    require('https').globalAgent.options.rejectUnauthorized = opts.rejectUnauthorized;
  }
  return ioclient.connect(opts.url);
};
