// Generated by CoffeeScript 1.6.3
var testable;

testable = void 0;

module.exports._ticker = function() {
  return testable;
};

module.exports.ticker = function(config) {
  var api, local;
  if (config == null) {
    config = {};
  }
  config.ticks || (config.ticks = {});
  testable = local = {
    notifier: void 0,
    timers: {},
    register: function(notifier, opts) {
      var key, list, timers, _results;
      if (opts == null) {
        opts = {};
      }
      local.notifier = notifier;
      local.timers[notifier.title] = timers = {};
      list = {};
      for (key in config.ticks) {
        list[key] = config.ticks[key];
      }
      for (key in opts.ticks) {
        list[key] = opts.ticks[key];
      }
      _results = [];
      for (key in list) {
        _results.push((function(key) {
          var tick;
          tick = list[key];
          if (tick.interval == null) {
            tick.interval = 1000;
          }
          tick.seq = 0;
          return timers[key] = {
            interval: tick.interval,
            timer: setInterval((function() {
              return notifier.$tick(key, {
                seq: tick.seq++
              });
            }), tick.interval)
          };
        })(key));
      }
      return _results;
    }
  };
  return api = {
    register: local.register
  };
};
