// Generated by CoffeeScript 1.6.3
var testable;

testable = void 0;

module.exports._capsule = function() {
  return testable;
};

module.exports.capsule = function(config) {
  var Capsule;
  if (config == null) {
    config = {};
  }
  return testable = Capsule = (function() {
    function Capsule() {}

    Capsule.prototype.set = function(opts) {
      var key, local,
        _this = this;
      local = {};
      for (key in opts) {
        break;
      }
      if (opts.watched != null) {
        if (opts["protected"]) {
          process.stderr.write("cannot watch protected property:" + key);
        } else {
          Object.defineProperty(this, key, {
            enumerable: true,
            get: function() {
              return local[key];
            },
            set: function(value) {
              var previous;
              previous = local[key];
              local[key] = value;
              return opts.watched({
                property: key,
                from: previous,
                to: value,
                capsule: _this
              });
            }
          });
        }
      }
      this[key] = opts[key];
      if (opts.hidden != null) {
        Object.defineProperty(this, key, {
          enumerable: !opts.hidden
        });
      }
      if (opts["protected"] != null) {
        return Object.defineProperty(this, key, {
          writable: !opts["protected"]
        });
      }
    };

    return Capsule;

  })();
};
