// Generated by CoffeeScript 1.6.3
var capsule, deferred, v1;

v1 = require('node-uuid').v1;

deferred = require('also').deferred;

capsule = require('./capsule').capsule;

module.exports.lifecycle = function(type, config) {
  var local;
  if (config == null) {
    config = {};
  }
  return local = {
    Capsule: capsule(config),
    config: (function() {
      try {
        return config.capsule[type];
      } catch (_error) {}
    })(),
    cache: {},
    create: deferred(function(_arg, properties) {
      var assign, cap, done, key, resolve;
      resolve = _arg.resolve;
      if (properties == null) {
        properties = {};
      }
      cap = new local.Capsule;
      cap.set({
        _type: type,
        "protected": true,
        hidden: true
      });
      for (key in properties) {
        if (key !== type) {
          cap[key] = properties[key];
          continue;
        }
        assign = {};
        assign[key] = properties[key];
        assign["protected"] = true;
        cap.set(assign);
      }
      try {
        if (local.config.before) {
          done = function() {
            if (cap._uuid == null) {
              cap._uuid = v1();
            }
            return resolve(cap);
          };
          return local.config.before(done, cap);
        }
      } catch (_error) {}
      if (cap._uuid == null) {
        cap._uuid = v1();
      }
      return resolve(cap);
    })
  };
};
