// Generated by CoffeeScript 1.6.3
var capsule, deferred, pipeline, testable, _ref;

_ref = require('also'), deferred = _ref.deferred, pipeline = _ref.pipeline;

capsule = require('./capsule').capsule;

testable = void 0;

module.exports._message = function() {
  return testable;
};

module.exports.message = function(type, config) {
  var local, thisConfig;
  if (config == null) {
    config = {};
  }
  thisConfig = {};
  try {
    thisConfig = config.messages[type];
  } catch (_error) {}
  local = {
    Capsule: capsule(config),
    Message: {
      create: deferred(function(_arg, properties) {
        var after, assign, before, notify, reject, resolve;
        resolve = _arg.resolve, reject = _arg.reject, notify = _arg.notify;
        if (properties == null) {
          properties = {};
        }
        before = deferred(function(_arg1, msg) {
          var reject, resolve;
          resolve = _arg1.resolve, reject = _arg1.reject;
          Object.defineProperty(msg, '_type', {
            enumerable: false,
            writable: false,
            value: type
          });
          if (typeof thisConfig.beforeCreate !== 'function') {
            return resolve(msg);
          }
          return thisConfig.beforeCreate(function(error) {
            if (error != null) {
              return reject(error);
            }
            return resolve(msg);
          }, msg);
        });
        assign = function(msg) {
          var key;
          for (key in properties) {
            msg[key] = properties[key];
          }
          return msg;
        };
        after = deferred(function(_arg1, msg) {
          var reject, resolve;
          resolve = _arg1.resolve, reject = _arg1.reject;
          if (typeof thisConfig.afterCreate !== 'function') {
            return resolve(msg);
          }
          return thisConfig.afterCreate(function(error) {
            if (error != null) {
              return reject(error);
            }
            return resolve(msg);
          }, msg);
        });
        return pipeline([
          function() {
            return new local.Capsule;
          }, function(msg) {
            return before(msg);
          }, function(msg) {
            return assign(msg);
          }, function(msg) {
            return after(msg);
          }
        ]).then(resolve, reject, notify);
      })
    }
  };
  testable = local;
  return local.Message;
};
