// Generated by CoffeeScript 1.4.0
var config, handler;

handler = void 0;

module.exports = config = function(opts) {
  if (opts == null) {
    opts = {};
  }
  if (typeof opts.handler === 'undefined') {
    return handler = require('./default_handler');
  } else {
    return handler = opts.handler;
  }
};

Object.defineProperty(config, 'handler', {
  get: function() {
    return handler;
  }
});
