// Generated by CoffeeScript 1.4.0
var config, configure;

config = {};

module.exports = configure = function(opts) {
  if (opts == null) {
    opts = {};
  }
  config.source = opts.source;
  return config.messenger = opts.messenger;
};

Object.defineProperty(configure, 'config', {
  get: function() {
    return config;
  }
});
