// Generated by CoffeeScript 1.4.0
var handler;

try {
  handler = require("" + process.env.HOME + "/.notice/handler");
} catch (error) {
  handler = function(notification) {
    var test;
    return test = 'default notification handler';
  };
}

module.exports = handler;
