// Generated by CoffeeScript 1.4.0
var notice;

module.exports = notice = require('./notice/notify').send;

Object.defineProperty(notice, 'configure', {
  get: function() {
    return require('./notice/configure');
  },
  enumerable: true
});
