// Generated by CoffeeScript 1.4.0
var config;

config = require('./configure').config;

module.exports = {
  sendMessage: function() {
    return config.messenger({
      source: config.source
    });
  }
};
