// Generated by CoffeeScript 1.6.3
var client, hub, notifier;

notifier = require('./notice/notifier').notifier;

client = require('./notice/client').client;

hub = require('./notice/hub').hub;

module.exports = notifier;

module.exports.create = notifier().create;

module.exports.connect = client().create;

module.exports.listen = hub().create;
