// Generated by CoffeeScript 1.6.3
var testable;

testable = void 0;

module.exports._capsule = function() {
  return testable;
};

module.exports.capsule = function(config) {
  var Capsule;
  if (config == null) {
    config = {};
  }
  return testable = Capsule = (function() {
    function Capsule() {}

    Capsule.prototype.set = function(opts) {
      var key;
      for (key in opts) {
        null;
      }
      this[key] = opts[key];
      if (opts["protected"]) {
        return Object.defineProperty(this, key, {
          writable: false
        });
      }
    };

    return Capsule;

  })();
};
