// Generated by CoffeeScript 1.6.3
var testable;

testable = void 0;

module.exports._capsule = function() {
  return testable;
};

module.exports.capsule = function(config) {
  var Capsule;
  if (config == null) {
    config = {};
  }
  return testable = Capsule = (function() {
    function Capsule() {}

    return Capsule;

  })();
};
