// Generated by CoffeeScript 1.4.0
var config, configure, defaultSource;

config = {};

defaultSource = function() {
  return 'the calling module';
};

module.exports = configure = function(opts) {
  if (opts == null) {
    opts = {};
  }
  config.source = opts.source || defaultSource();
  return config.messenger = opts.messenger;
};

Object.defineProperty(configure, 'config', {
  get: function() {
    return config;
  }
});
