// Generated by CoffeeScript 1.4.0
var NotifierFactory, defaultMessenger, localMessenger;

localMessenger = require('./local_messenger');

defaultMessenger = require('./default_messenger');

NotifierFactory = require('./notifier_factory');

module.exports = function(opts, callback) {
  var messenger;
  opts || (opts = {});
  if (typeof opts.source === 'undefined') {
    throw new Error('Notice.configure(opts, callback) requires config.source');
  }
  if (typeof callback !== 'function') {
    throw new Error('Notice.configure(opts, callback) requires callback to receive configured notifier');
  }
  return messenger = localMessenger.find(opts.source) || opts.messenger || defaultMessenger;
};
