// Generated by CoffeeScript 1.4.0
var config, configure, defaultMessenger, localMessenger;

config = {};

localMessenger = require('./local_messenger');

defaultMessenger = require('./default_messenger');

module.exports = configure = function(opts, callback) {
  opts || (opts = {});
  if (typeof opts.source === 'undefined') {
    throw new Error('Notice.configure(opts, callback) requires opts.source');
  }
  if (typeof callback !== 'function') {
    throw new Error('Notice.configure(opts, callback) requires callback to receive configured notifier');
  }
  config.source = opts.source;
  return config.messenger = localMessenger() || opts.messenger || defaultMessenger;
};

Object.defineProperty(configure, 'config', {
  get: function() {
    return config;
  }
});
