// Generated by CoffeeScript 1.4.0
var ioclient;

ioclient = require('socket.io-client');

module.exports = {
  connect: function() {
    var accepted, arg, callback, opts, socket, _i, _len;
    opts = arguments['0'] || {};
    if (opts instanceof Function) {
      opts = {};
    }
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      arg = arguments[_i];
      callback = arg;
    }
    opts.port || (opts.port = 10001);
    opts.address || (opts.address = 'localhost');
    opts.transport || (opts.transport = 'http');
    accepted = false;
    socket = ioclient.connect("" + opts.transport + "://" + opts.address + ":" + opts.port);
    socket.on('error', function(error) {
      if (typeof callback === 'function') {
        if (!accepted) {
          return callback(error, null);
        }
      }
    });
    socket.on('accept', function() {
      accepted = true;
      if (typeof callback === 'function') {
        return callback(null, socket);
      }
    });
    return socket.on('connect', function() {
      return socket.emit('handshake', opts.secret || '', {
        context: 'pending'
      });
    });
  }
};
