// Generated by CoffeeScript 1.4.0
var ioclient;

ioclient = require('socket.io-client');

module.exports = function() {
  var arg, callback, connected, opts, socket, _i, _len;
  opts = arguments['0'] || {};
  for (_i = 0, _len = arguments.length; _i < _len; _i++) {
    arg = arguments[_i];
    callback = arg;
  }
  opts.port || (opts.port = 10001);
  opts.hostname || (opts.hostname = 'localhost');
  opts.transport || (opts.transport = 'http');
  socket = ioclient.connect("" + opts.transport + "://" + opts.hostname + ":" + opts.port);
  connected = false;
  socket.on('error', function(error) {
    if (typeof callback === 'function') {
      if (!connected) {
        return callback(error, null);
      }
    }
  });
  return socket.on('connect', function() {
    connected = true;
    return callback();
  });
};
