// Generated by CoffeeScript 1.4.0
var socket;

socket = require('socket.io-client');

module.exports = function(opts) {
  if (opts == null) {
    opts = {};
  }
  opts.port || (opts.port = 10001);
  opts.hostname || (opts.hostname = 'localhost');
  opts.transport || (opts.transport = 'https');
  return socket.connect("" + opts.transport + "://" + opts.hostname + ":" + opts.port);
};
