// Generated by CoffeeScript 1.6.3
var support, uuid;

uuid = require('node-uuid');

support = require('./support');

module.exports = {
  asUniq: function(fn) {
    return function() {
      var arg, inject, _i, _len;
      inject = [uuid.v1()];
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        arg = arguments[_i];
        inject.push(arg);
      }
      return fn.apply(this, inject);
    };
  }
};
