// Generated by CoffeeScript 1.4.0
var support;

support = require('./support');

module.exports = {
  onceIfString: function(fn) {
    return (function(done) {
      return function(value) {
        if (!done) {
          if (done = typeof value === 'string') {
            return fn(value);
          }
        }
      };
    })(false);
  },
  isFn: function(fn) {
    return (function() {
      return function(value) {
        if (typeof value === 'function') {
          return fn(value);
        }
        return false;
      };
    })();
  },
  isMiddleware: function(fn) {
    return function(middleware) {
      var next;
      if (!(next = support.argsOf(middleware)[1])) {
        return function() {
          return false;
        };
      }
      if (!support.callsFn(next, middleware)) {
        return function() {
          return false;
        };
      }
      return fn(middleware);
    };
  }
};
