// Generated by CoffeeScript 1.4.0

module.exports = {
  onceIfString: function(fn) {
    return (function(done) {
      return function(value) {
        if (!done) {
          if (done = typeof value === 'string') {
            return fn(value);
          }
        }
      };
    })(false);
  },
  isFn: function(fn) {
    return (function() {
      return function(value) {
        if (typeof value === 'function') {
          return fn(value);
        }
        return false;
      };
    })();
  }
};
