// Generated by CoffeeScript 1.4.0
var path;

path = require('path');

module.exports = function() {
  var line, match, _i, _len, _ref;
  _ref = Error.apply(this).stack.split('\n');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    line = _ref[_i];
    if (!(match = line.match(/\((.*?)\/node_modules\//))) {
      continue;
    }
    return path.basename(match[1]);
  }
  return 'default';
};
