// Generated by CoffeeScript 1.4.0

module.exports = function(msg) {
  return console.log("[default messenger]/notice/%s/%s from:'%s' label:'%s' description:'%s'", msg.context.type, msg.context.tenor, msg.source.ref, msg.content.label, msg.content.description);
};
