// Generated by CoffeeScript 1.6.3
module.exports.terminal = function(error, reject, callback) {
  if (typeof reject === 'function') {
    reject(error);
  }
  if (typeof callback === 'function') {
    return callback(error);
  }
};

module.exports.reservedCapsule = function(type) {
  var error;
  return error = new Error("notice: '" + type + "' is a reserved capsule type");
};

module.exports.missingConfig = function(opt, module) {
  var error;
  return error = new Error("notice: " + module + " requires opt " + opt);
};

module.exports.undefinedArg = function(arg, functionSignature) {
  var error;
  if (functionSignature != null) {
    return error = new Error("notice: " + functionSignature + " requires arg " + arg);
  }
  return error = new Error("notice: requires arg " + arg);
};

module.exports.alreadyDefined = function(thingType, thingName) {
  var error;
  return error = new Error("notice: " + thingType + " '" + thingName + "' is already defined");
};

module.exports.disconnected = function(originName) {
  var error;
  return error = new Error("notice: origin '" + originName + "' disconnected");
};

module.exports.connectRejected = function(originName, rejection) {
  var error;
  switch (rejection.reason) {
    case 'already connected':
      return error = new Error("notice: origin '" + originName + "' rejected - " + rejection.reason + " from " + rejection.pid + "." + rejection.hostname);
  }
  return error = new Error("notice: origin '" + originName + "' rejected - " + rejection.reason);
};
