// Generated by CoffeeScript 1.4.0
var listen;

listen = require('./listen');

module.exports.create = function(hubName, opts) {
  var hub, io;
  if (opts == null) {
    opts = {};
  }
  if (typeof hubName !== 'string') {
    throw new Error('Notifier.listen( hubName, opts ) requires hubName as string');
  }
  opts || (opts = {});
  hub = {
    socket: {},
    context: {}
  };
  io = listen(opts, function(error, address) {});
  io.on('connection', function(socket) {
    socket.on('handshake', function(secret, context) {
      if (secret === opts.secret) {
        hub.socket[socket.id] = socket;
        return hub.context[socket.id] = context;
      } else {
        return socket.disconnect();
      }
    });
    return socket.on('disconnect', function() {});
  });
  return hub;
};
