// Generated by CoffeeScript 1.4.0
var listen;

listen = require('./listen');

module.exports.create = function(hubName, opts, callback) {
  var io, _base;
  if (typeof hubName !== 'string') {
    throw new Error('Notifier.listen( hubName, opts ) requires hubName as string');
  }
  opts || (opts = {});
  opts.listen || (opts.listen = {});
  (_base = opts.listen).secret || (_base.secret = '');
  opts.hub = {};
  io = listen({
    address: opts.listen.address,
    port: opts.listen.port,
    cert: opts.listen.cert,
    key: opts.listen.key
  }, function(error, address) {
    opts.hub.listening = address;
    if (typeof callback === 'function') {
      return callback(error, null);
    }
  });
  io.on('connection', function(socket) {
    socket.on('handshake', function(secret, context) {
      if (secret === opts.listen.secret) {
        return socket.emit('accept');
      } else {
        return socket.disconnect();
      }
    });
    socket.on('info', function(payload) {
      return console.log('INFO', payload);
    });
    socket.on('event', function(payload) {
      return console.log('EVENT', payload);
    });
    return socket.on('disconnect', function() {});
  });
  return opts;
};
