// Generated by CoffeeScript 1.4.0
var http, listen, start;

http = require('http');

start = function() {
  return http.createServer();
};

listen = function(opts) {
  var server, _base, _base1;
  if (opts == null) {
    opts = {};
  }
  opts.listen || (opts.listen = {});
  (_base = opts.listen).port || (_base.port = 10001);
  (_base1 = opts.listen).iface || (_base1.iface = 'localhost');
  server = opts.server || start();
  if (opts.server == null) {
    return server.listen(opts.listen.port, opts.listen.iface, function() {
      return console.log('listening', server.address());
    });
  }
};

module.exports = listen;
