// Generated by CoffeeScript 1.4.0
var fs, http, https, listen, start, transport;

http = require('http');

https = require('https');

fs = require('fs');

transport = 'http';

start = function(opts) {
  if ((opts.cert != null) && (opts.key != null)) {
    try {
      transport = 'https';
      return https.createServer({
        key: fs.readFileSync(opts.key),
        cert: fs.readFileSync(opts.cert)
      });
    } catch (error) {
      console.log(error);
      transport = 'http';
    }
  }
  return http.createServer();
};

listen = function(opts) {
  var server;
  if (opts == null) {
    opts = {};
  }
  opts.port || (opts.port = 10001);
  opts.iface || (opts.iface = 'localhost');
  server = opts.server || start(opts);
  if (opts.server == null) {
    return server.listen(opts.port, opts.iface, function() {
      var address, port, _ref;
      _ref = server.address(), address = _ref.address, port = _ref.port;
      return console.log('listening @ %s://%s:%s', transport, address, port);
    });
  }
};

module.exports = listen;
