// Generated by CoffeeScript 1.4.0
var validate;

validate = function(arrayOfMiddleware) {
  return arrayOfMiddleware;
};

module.exports = function() {
  var key, middleware, processed;
  try {
    middleware = require("" + process.env.HOME + "/.notice/middleware");
    processed = {};
    if (middleware.all != null) {
      processed.all = middleware.all;
    }
    for (key in middleware) {
      if (key === 'all') {
        continue;
      }
      processed[key] = typeof middleware[key] === 'function' ? {
        matchAll: {
          origin: key
        },
        fn: middleware[key]
      } : middleware[key] instanceof Array ? validate(middleware[key]) : void 0;
    }
    return processed;
  } catch (error) {
    return {};
  }
};
