// Generated by CoffeeScript 1.4.0

module.exports = function() {
  var key, middleware, processed;
  try {
    middleware = require("" + process.env.HOME + "/.notice/middleware");
    processed = {};
    if (middleware.all != null) {
      processed.all = middleware.all;
    }
    for (key in middleware) {
      if (key === 'all') {
        continue;
      }
      processed[key] = middleware[key];
    }
    return processed;
  } catch (error) {
    return {};
  }
};
