// Generated by CoffeeScript 1.4.0
var inflection;

inflection = require('inflection');

module.exports = {
  find: function(source) {
    var messenger;
    try {
      messenger = require("" + process.env.HOME + "/.notice/messengers");
      if (typeof messenger[source] !== 'function') {
        return null;
      }
      return messenger[source];
    } catch (error) {
      return null;
    }
  }
};
