// Generated by CoffeeScript 1.4.0

module.exports = function() {
  var middleware, processed;
  try {
    middleware = require("" + process.env.HOME + "/.notice/middleware");
    processed = {};
    if (middleware.all != null) {
      processed.all = middleware.all;
    }
    return processed;
  } catch (error) {
    return {};
  }
};
