// Generated by CoffeeScript 1.6.3
var deferred, pipeline, testable, _ref;

_ref = require('also'), deferred = _ref.deferred, pipeline = _ref.pipeline;

testable = void 0;

module.exports._message = function() {
  return testable;
};

module.exports.message = function(config) {
  var local;
  if (config == null) {
    config = {};
  }
  local = {
    Message: {
      create: deferred(function(_arg, properties) {
        var after, assign, before, notify, reject, resolve;
        resolve = _arg.resolve, reject = _arg.reject, notify = _arg.notify;
        if (properties == null) {
          properties = {};
        }
        before = deferred(function(_arg1, msg) {
          var reject, resolve;
          resolve = _arg1.resolve, reject = _arg1.reject;
          if (properties._type == null) {
            properties._type = 'event';
          }
          Object.defineProperty(msg, '_type', {
            enumerable: false,
            writable: false,
            value: properties._type
          });
          if (typeof config.beforeCreate !== 'function') {
            return resolve(msg);
          }
          return config.beforeCreate(msg, function(error) {
            if (error != null) {
              return reject(error);
            }
            return resolve(msg);
          });
        });
        assign = function(msg) {
          var key;
          for (key in config.properties) {
            if (key === '_type') {
              continue;
            }
            if (config.properties[key]["default"] != null) {
              msg[key] = config.properties[key]["default"];
              if (config.properties[key].hidden) {
                Object.defineProperty(msg, key, {
                  enumerable: false
                });
              }
            }
          }
          for (key in properties) {
            msg[key] = properties[key];
          }
          return msg;
        };
        after = deferred(function(_arg1, msg) {
          var reject, resolve;
          resolve = _arg1.resolve, reject = _arg1.reject;
          if (typeof config.afterCreate !== 'function') {
            return resolve(msg);
          }
          return config.afterCreate(msg, function(error) {
            if (error != null) {
              return reject(error);
            }
            return resolve(msg);
          });
        });
        return pipeline([
          function() {
            return before({});
          }, function(msg) {
            return assign(msg);
          }, function(msg) {
            return after(msg);
          }
        ]).then(resolve, reject, notify);
      })
    }
  };
  testable = local;
  return local.Message;
};
