// Generated by CoffeeScript 1.4.0
var Message;

module.exports = Message = (function() {

  function Message(label, description) {
    var content;
    content = {
      label: typeof label === 'string' ? label : void 0,
      description: typeof description === 'string' ? description : void 0
    };
    Object.defineProperty(this, 'content', {
      get: function() {
        return {
          label: content.label,
          description: content.description
        };
      }
    });
    Object.defineProperty(this, 'label', {
      get: function() {
        return content.label;
      },
      set: function(value) {
        if (content.label == null) {
          if (typeof value === 'string') {
            return content.label = value;
          }
        }
      }
    });
    Object.defineProperty(this, 'description', {
      get: function() {
        return content.description;
      },
      set: function(value) {
        if (content.description == null) {
          if (typeof value === 'string') {
            return content.description = value;
          }
        }
      }
    });
  }

  return Message;

})();
