// Generated by CoffeeScript 1.4.0
var config, notify;

config = require('./configure').config;

module.exports = notify = {
  format: function(context, args) {
    var content;
    try {
      if (args[0].formatted) {
        return args[0];
      }
    } catch (_error) {}
    content = {};
    if (typeof args[0] === 'string') {
      content.label = args[0];
    } else {
      content = args[0];
    }
    if (typeof args[1] === 'string') {
      content.description = args[1];
    }
    if (typeof context.type === 'undefined') {
      context.type = 'event';
    }
    return {
      context: context,
      source: {
        time: Date.now(),
        ref: config.source
      },
      content: content,
      formatted: true
    };
  },
  send: function(label, description) {
    return config.messenger(notify.format({}, arguments));
  }
};
