// Generated by CoffeeScript 1.4.0
var config, os;

os = require('os');

config = require('./configure').config;

module.exports = {
  send: function(msg) {
    if (msg == null) {
      msg = {};
    }
    msg.source = {
      time: Date.now(),
      ref: config.source
    };
    return config.messenger(msg);
  }
};
