// Generated by CoffeeScript 1.4.0
var NotifierFactory;

module.exports = NotifierFactory = (function() {

  function NotifierFactory(moo) {
    this.moo = moo;
  }

  NotifierFactory.prototype.create = function(config, callback) {
    config || (config = {});
    if (typeof config.messenger !== 'function') {
      throw new Error("" + this.constructor.name + " requires config.messenger");
    }
    return callback(null, function() {
      return config.messenger.apply(null, arguments);
    });
  };

  return NotifierFactory;

})();
