// Generated by CoffeeScript 1.4.0
var NotifierFactory, pipeline;

pipeline = require('when/pipeline');

module.exports = NotifierFactory = (function() {

  function NotifierFactory(moo) {
    this.moo = moo;
    this.pipeline = [];
  }

  NotifierFactory.prototype.create = function(config, callback) {
    var notifier,
      _this = this;
    config || (config = {});
    if (typeof config.messenger !== 'function') {
      throw new Error("" + this.constructor.name + " requires config.messenger");
    }
    notifier = function() {
      var message;
      message = {
        content: {}
      };
      message.content.label = arguments[0];
      message.content.description = arguments[1];
      return config.messenger(message);
    };
    notifier.use = function(fn) {
      return _this.pipeline.push(fn);
    };
    return callback(null, notifier);
  };

  return NotifierFactory;

})();
