// Generated by CoffeeScript 1.6.3
var support;

module.exports = support = {
  argsOf: function(fn) {
    var error;
    try {
      return fn.toString().match(/function\W*\((.*)\)/)[1].split(',').map(function(arg) {
        return arg.trim();
      }).filter(function(arg) {
        return arg !== '';
      });
    } catch (_error) {
      error = _error;
      return [];
    }
  },
  callsFn: function(fn, Fn) {
    return Fn.toString().match(new RegExp("" + fn + "\W*\\(\W*\\)")) instanceof Array;
  }
};
