// Generated by CoffeeScript 1.4.0
var asUniq, defer;

asUniq = require('./decorators').asUniq;

defer = require('when').defer;

exports.createTask = asUniq(function(id, title, opts, notifier) {
  var task;
  console.log({
    createTask: arguments
  });
  task = defer();
  Object.defineProperty(task.promise, 'id', {
    enumerable: true,
    writable: false,
    value: id
  });
  opts.id = id;
  notifier(title, opts, 'task', 'normal');
  return task.promise;
});
