// Generated by CoffeeScript 1.4.0
var asUniq;

asUniq = require('./decorators').asUniq;

module.exports = {
  create: asUniq(function(id, title) {
    return console.log('create task', {
      id: id,
      title: title
    });
  })
};
