// Generated by CoffeeScript 1.4.0
var asUniq;

asUniq = require('./decorators').asUniq;

exports.create = asUniq(function(id, notifier, title, opts) {
  var task;
  console.log({
    createTask: arguments
  });
  task = new Object;
  return Object.defineProperty(task, 'id', {
    enumerable: true,
    writable: false,
    value: id
  });
});
