// Generated by CoffeeScript 1.4.0
var Task, asUniq, _class;

asUniq = require('./decorators').asUniq;

module.exports = Task = (function() {

  function Task() {
    return _class.apply(this, arguments);
  }

  _class = asUniq(function(id, title, opts) {
    this.id = id;
    this.title = title;
    this.opts = opts;
  });

  return Task;

})();
