// Generated by CoffeeScript 1.4.0
var isFn;

isFn = require('./decorators').isFn;

module.exports = {
  middleware: isFn(function(fn) {
    var fnArgs, nextWasCalled;
    try {
      fnArgs = fn.toString().match(/^function\W*\(\W*(.*)\W*,\W*(.*)\W*\)/).slice(1, 3).map(function(arg) {
        return arg.trim();
      });
    } catch (error) {
      return false;
    }
    nextWasCalled = new RegExp("" + fnArgs[1] + "\W*\\(\W*\\)");
    if (!fn.toString().match(nextWasCalled)) {
      return false;
    }
    return true;
  })
};
