// Generated by CoffeeScript 1.4.0
var requiresFn;

requiresFn = function(fn) {
  return (function() {
    return function(value) {
      if (typeof value === 'function') {
        return fn(value);
      }
      return false;
    };
  })();
};

module.exports = {
  middleware: requiresFn(function(fn) {
    var fnArgs, nextWasCalled;
    try {
      fnArgs = fn.toString().match(/^function\W*\(\W*(.*)\W*,\W*(.*)\W*\)/).slice(1, 3).map(function(arg) {
        return arg.trim();
      });
    } catch (error) {
      return false;
    }
    nextWasCalled = new RegExp("" + fnArgs[1] + "\W*\\(\W*\\)");
    if (!fn.toString().match(nextWasCalled)) {
      return false;
    }
    return true;
  })
};
