// Generated by CoffeeScript 1.6.3
module.exports.authenticator = function(config) {
  var authenticateFn, decodeAuth, requestAuth;
  if (config == null) {
    config = {};
  }
  authenticateFn = (function() {
    try {
      return config.manager.authenticate;
    } catch (_error) {}
  })();
  requestAuth = function(response) {
    response.writeHead(401, {
      'www-authenticate': 'BASIC'
    });
    return response.end();
  };
  decodeAuth = function(authorization, request, response) {
    var decoded, error, input, password, username, _ref;
    try {
      decoded = new Buffer(authorization, 'base64').toString('utf8');
      _ref = decoded.match(/(.*):(.*)/), input = _ref[0], username = _ref[1], password = _ref[2];
      return {
        username: username,
        password: password
      };
    } catch (_error) {
      error = _error;
      return requestAuth(response);
    }
  };
  return function(requestHandler) {
    return function(request, response) {
      var authorization, password, username, _ref;
      try {
        authorization = request.headers.authorization;
      } catch (_error) {}
      if (authorization == null) {
        return requestAuth(response);
      }
      if (!(_ref = decodeAuth(authorization, request, response), username = _ref.username, password = _ref.password, _ref)) {
        return;
      }
      return authenticateFn(username, password, function(error, result) {
        return requestHandler(request, response);
      });
    };
  };
};
