// Generated by CoffeeScript 1.6.3
module.exports.authenticator = function(config) {
  var authenticateFn;
  if (config == null) {
    config = {};
  }
  authenticateFn = (function() {
    try {
      return config.manager.authenticate;
    } catch (_error) {}
  })();
  return function(request, response) {
    return authenticateFn();
  };
};
