// Generated by CoffeeScript 1.6.3
var memoryUsage;

memoryUsage = process.memoryUsage;

module.exports.health = function(capsule, callback) {
  capsule.memory = memoryUsage();
  return callback();
};
