// Generated by CoffeeScript 1.6.3
var authenticator, missingConfig, start, testable;

authenticator = require('./authenticator').authenticator;

missingConfig = require('../notice/errors').missingConfig;

start = require('../notice/hub/listener').start;

testable = void 0;

module.exports._manager = function() {
  return testable;
};

module.exports.manager = function(config) {
  var address, api, authenticate, listen, local, opts, port, server, transport, _ref;
  if (config == null) {
    config = {};
  }
  try {
    listen = config.manager.listen;
  } catch (_error) {}
  authenticate = authenticator(config);
  if (listen == null) {
    throw missingConfig('config.manager.listen', 'manager');
  }
  if (typeof listen.port !== 'number') {
    throw missingConfig('config.manager.listen.port', 'manager');
  }
  testable = local = {
    register: function(hubContext) {
      return console.log(hubContext);
    },
    routes: {}
  };
  port = listen.port;
  address = listen.hostname != null ? listen.hostname : '127.0.0.1';
  opts = {};
  opts.key = listen.key;
  opts.cert = listen.cert;
  _ref = start(opts, authenticate(function(request, response) {
    response.writeHead(200);
    return response.end('okgood');
  })), server = _ref.server, transport = _ref.transport;
  server.listen(port, address, function() {
    var _ref1;
    _ref1 = server.address(), address = _ref1.address, port = _ref1.port;
    return console.log('API @ %s://%s:%s', transport, address, port);
  });
  return api = {
    register: local.register
  };
};
