// Generated by CoffeeScript 1.6.3
var testable;

testable = void 0;

module.exports._recursor = function() {
  return testable;
};

module.exports.recursor = function(local, type) {
  return testable = function(_arg, request, response, statusCode) {
    var deeper, notifier, result, searialized, uuid;
    uuid = _arg[0], deeper = _arg[1];
    if (statusCode == null) {
      statusCode = 200;
    }
    if (request.method !== 'GET') {
      return local.methodNotAllowed(response);
    }
    if (!local.hubContext.uuids[uuid]) {
      return local.objectNotFound(response);
    }
    notifier = local.hubContext.uuids[uuid];
    searialized = notifier.serialize(2);
    if (searialized[type] == null) {
      return local.objectNotFound(response);
    }
    result = JSON.stringify(searialized[type]);
    response.writeHead(statusCode);
    response.write(result);
    return response.end();
  };
};
