// Generated by CoffeeScript 1.6.3
var testable;

testable = void 0;

module.exports._ticker = function() {
  return testable;
};

module.exports.ticker = function(config) {
  var api, local;
  if (config == null) {
    config = {};
  }
  testable = local = {
    notifier: void 0,
    timers: {},
    register: function(notifier, opts) {
      var key, timers, _results;
      local.notifier = notifier;
      local.timers[notifier.title] = timers = {};
      _results = [];
      for (key in opts.ticks) {
        _results.push((function(key) {
          var tick;
          tick = opts.ticks[key];
          if (tick.interval == null) {
            tick.interval = 1000;
          }
          return timers[key] = {
            interval: tick.interval,
            timer: setInterval((function() {
              return notifier.$$tick(key);
            }), tick.interval)
          };
        })(key));
      }
      return _results;
    }
  };
  return api = {
    register: local.register
  };
};
