// Generated by CoffeeScript 1.6.3
module.exports.ticks = function(config) {
  var local;
  if (config == null) {
    config = {};
  }
  return local = {
    notifier: void 0,
    timers: {},
    register: function(opts, notifier) {
      var key, timers, _results;
      local.notifier = notifier;
      local.timers[notifier.title] = timers = {};
      _results = [];
      for (key in opts.ticks) {
        _results.push((function(key) {
          var tick;
          tick = opts.ticks[key];
          return timers[key] = setInterval((function() {
            return notifier.$$tick(key);
          }), tick.interval);
        })(key));
      }
      return _results;
    }
  };
};
