// Generated by CoffeeScript 1.6.3
var NotableTool;

module.exports = NotableTool = (function() {
  function NotableTool() {
    this.exposedProperty = 'value';
    Object.defineProperty(this, 'apiExposedFunction', {
      enumerable: true,
      get: function() {
        var exported;
        exported = function(opts, callback) {
          return setTimeout((function() {
            return callback(null, {
              property1: 'value1',
              property2: '1value'
            });
          }), 3000);
        };
        exported.$$notable = {};
        return exported;
      },
      set: function(value) {
        return function() {
          return function() {
            return function() {
              return "\nhas not been thought about to any depth yet,\nother than a vague sense,\nof wanting to PUT POST in\n";
            };
          };
        };
      }
    });
  }

  return NotableTool;

})();
