// Generated by CoffeeScript 1.6.3
var Infinity, NotableTool;

module.exports = NotableTool = (function() {
  function NotableTool() {
    this.exposedProperty = 'value';
    Object.defineProperty(this, 'apiExposedFunction', {
      enumerable: true,
      get: function() {
        var exported;
        exported = function(opts, callback) {
          return setTimeout((function() {
            return callback(null, Infinity);
          }), 3000);
        };
        exported.$$notable = {};
        return exported;
      },
      set: function(value) {
        return function() {
          return function() {
            return function() {
              return "\nhas not been thought about to any depth yet,\nother than a vague sense,\nof wanting to PUT POST in\n";
            };
          };
        };
      }
    });
  }

  return NotableTool;

})();

Infinity = {
  endlessly: {
    more: 'stuff'
  },
  "with": {
    another: new NotableTool('inside it')
  }
};
