// Generated by CoffeeScript 1.6.3
var Infinity, NoticeableClass;

module.exports = NoticeableClass = (function() {
  function NoticeableClass() {
    this.apiProperty = {
      deeper: {
        and: {
          deeper: 'value'
        }
      }
    };
    this.apiFunction = function(opts, callback) {
      return setTimeout((function() {
        return callback(null, Infinity);
      }), 400);
    };
    this.apiFunction.$$notice = {};
    this.apiFunction2 = function(opts, callback) {
      return callback(null, {
        "this": 1
      });
    };
    this.apiFunction2.$$notice = {};
  }

  return NoticeableClass;

})();

Infinity = {
  endlessly: {
    more: 'stuff'
  },
  "with": {
    another: new NoticeableClass('inside it')
  }
};
