// Generated by CoffeeScript 1.6.3
var Infinity, NoticeableClass;

module.exports = NoticeableClass = (function() {
  function NoticeableClass() {
    this.apiProperty = {
      deeper: 'value'
    };
    this.apiFunction = function(opts, callback) {
      return setTimeout((function() {
        return callback(null, {
          async: {
            jump: {
              "in": 'path'
            }
          }
        });
      }), 400);
    };
    this.apiFunction.$$notice = {};
    this.array = ['this', 'is', 'listified'];
  }

  return NoticeableClass;

})();

Infinity = {
  endlessly: {
    more: 'stuff'
  },
  "with": {
    another: new NoticeableClass('inside it')
  }
};
